import type { SiteInfo, Category } from '@/types';

export const allSites: SiteInfo[] = [
  {
    id: 'metals',
    name: 'Alaska Metals Exchange',
    url: 'https://alaskametalsexchange.com',
    description: 'Premier dealer in gold, silver, and platinum bullion',
    category: 'Commerce',
    icon: '🥇',
    color: 'bg-yellow-500',
  },
  {
    id: 'boats',
    name: 'Alaskan Boats',
    url: 'https://alaskanboats.com',
    description: 'Buy and sell boats across Alaska',
    category: 'Commerce',
    icon: '🚤',
    color: 'bg-blue-500',
  },
  {
    id: 'mining-equipment',
    name: 'Alaska Mining Equipment',
    url: 'https://alaskaminingequipment.com',
    description: 'Heavy equipment for mining operations',
    category: 'Commerce',
    icon: '🏗️',
    color: 'bg-orange-500',
  },
  {
    id: 'guide-search',
    name: 'Alaska Guide Search',
    url: 'https://akguidesearch.com',
    description: 'Find and book outdoor adventure guides',
    category: 'Services',
    icon: '🎣',
    color: 'bg-green-500',
  },
  {
    id: 'drone-survey',
    name: 'Alaska Drone Survey',
    url: 'https://alaskadronesurvey.com',
    description: 'Professional aerial photography and surveying',
    category: 'Services',
    icon: '📸',
    color: 'bg-purple-500',
  },
  {
    id: 'alaska-listings',
    name: 'Alaska Listings',
    url: 'https://alaskalistings.com',
    description: 'General marketplace for Alaska',
    category: 'Marketplace',
    icon: '🛍️',
    color: 'bg-indigo-500',
  },
  {
    id: 'bb-listings',
    name: 'BB Listings',
    url: 'https://bblistings.com',
    description: 'Bristol Bay area classifieds',
    category: 'Marketplace',
    icon: '📋',
    color: 'bg-cyan-500',
  },
  {
    id: 'anchorage-listings',
    name: 'Anchorage Listings',
    url: 'https://anchoragelistings.com',
    description: 'Anchorage area marketplace',
    category: 'Marketplace',
    icon: '🏙️',
    color: 'bg-slate-500',
  },
  {
    id: 'chugach-listings',
    name: 'Chugach Listings',
    url: 'https://chugachlistings.com',
    description: 'Chugach region classifieds',
    category: 'Marketplace',
    icon: '⛰️',
    color: 'bg-emerald-500',
  },
  {
    id: 'tongass-listings',
    name: 'Tongass Listings',
    url: 'https://tongasslistings.com',
    description: 'Tongass National Forest area',
    category: 'Marketplace',
    icon: '🌲',
    color: 'bg-teal-500',
  },
  {
    id: 'prudhoe-listings',
    name: 'Prudhoe Listings',
    url: 'https://prudhoelistings.com',
    description: 'Prudhoe Bay area marketplace',
    category: 'Marketplace',
    icon: '🛢️',
    color: 'bg-gray-500',
  },
  {
    id: 'alcan-listings',
    name: 'Alcan Listings',
    url: 'https://alcanlistings.com',
    description: 'Alaska-Canada Highway corridor',
    category: 'Marketplace',
    icon: '🛣️',
    color: 'bg-amber-500',
  },
  {
    id: 'foundation',
    name: 'Alaska Foundation',
    url: 'https://alaskafoundation.org',
    description: 'Supporting Alaska wilderness conservation',
    category: 'Non-Profit',
    icon: '❤️',
    color: 'bg-red-500',
  },
  {
    id: 'gold-news',
    name: 'Alaska Gold News',
    url: 'https://alaskagoldnews.com',
    description: 'News and updates from Alaska',
    category: 'Media',
    icon: '📰',
    color: 'bg-yellow-600',
  },
];

export const categories: Category[] = [
  {
    id: 'precious-metals',
    name: 'Precious Metals & Gold',
    icon: '🥇',
    description: 'Gold, silver, platinum, and investment-grade metals',
    slug: 'precious-metals',
    color: 'bg-yellow-500',
  },
  {
    id: 'boats',
    name: 'Boats & Marine Equipment',
    icon: '🚤',
    description: 'Fishing vessels, recreational boats, and marine gear',
    slug: 'boats',
    color: 'bg-blue-500',
  },
  {
    id: 'mining-equipment',
    name: 'Mining & Heavy Equipment',
    icon: '🏗️',
    description: 'Bulldozers, excavators, and mining machinery',
    slug: 'mining-equipment',
    color: 'bg-orange-500',
  },
  {
    id: 'guides',
    name: 'Outdoor Guides & Adventures',
    icon: '🎣',
    description: 'Hunting, fishing, and wilderness adventure guides',
    slug: 'guides',
    color: 'bg-green-500',
  },
  {
    id: 'drone-services',
    name: 'Drone Survey Services',
    icon: '📸',
    description: 'Aerial photography, mapping, and surveying',
    slug: 'drone-services',
    color: 'bg-purple-500',
  },
  {
    id: 'real-estate',
    name: 'Real Estate Listings',
    icon: '🏠',
    description: 'Land, cabins, and properties across Alaska',
    slug: 'listings',
    color: 'bg-indigo-500',
  },
  {
    id: 'marketplace',
    name: 'General Marketplace',
    icon: '🛍️',
    description: 'Everything else - vehicles, gear, and more',
    slug: 'listings',
    color: 'bg-slate-500',
  },
  {
    id: 'foundation',
    name: 'Alaska Foundation',
    icon: '❤️',
    description: 'Support wilderness conservation efforts',
    slug: 'foundation',
    color: 'bg-red-500',
  },
];
